version: '3.8'

volumes:
  pgdata:

networks:
  app-tier:
    driver: bridge


services:
  postgres:
    image: postgres:17.0-alpine
    restart: always
    ports:
      - 15432:5432
    networks:
      - app-tier
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES__USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
      - POSTGRES_DB=${POSTGRES__DB}
    volumes:
      - ./data/pg_history:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES__USERNAME} -d ${POSTGRES__DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  hasura:
    image: hasura/graphql-engine:v2.36.0
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-tier
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${POSTGRES__USERNAME}:${POSTGRES__PASSWORD}@postgres:5432/${POSTGRES__DB}
      ## this env var can be used to add the above postgres database to Hasura as a data source
      PG_DATABASE_URL: postgres://${POSTGRES__USERNAME}:${POSTGRES__PASSWORD}@postgres:5432/${POSTGRES__DB}
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## admin secret for security
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET:-myadminsecretkey}
      ## enable console assets on server
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: /srv/console-assets
